sudo: required
services:
    - docker
    
before_install:
    - docker build -t nitinrai17/fibcalculator_client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nitinrai17/fibcalculator_client-test npm run test -- --coverage    

after_success: 
    - docker build -t nitinrai17/fibcalculator-client ./client
    - docker build -t nitinrai17/fibcalculator-nginx ./nginx
    - docker build -t nitinrai17/fibcalculator-server ./server
    - docker build -t nitinrai17/fibcalculator-worker ./worker
    # login into docker hub 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #  take those image and push into the docker hub 
    - docker push  nitinrai17/fibcalculator-client 
    - docker push  nitinrai17/fibcalculator-nginx 
    - docker push  nitinrai17/fibcalculator-server
    - docker push  nitinrai17/fibcalculator-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: FiboCalculator
    env: Fibocalculator-env
    bucket_name: elasticbeanstalk-us-east-2-117771544263
    bucket_path: FiboCalculator
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
