sudo: required
services:
    - docker
    
before_install:
    - docker build -t nitinrai17/fibcalculator_client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nitinrai17/fibcalculator_client-test npm run test -- --coverage    

after_success: 
    - docker build -t nitinrai17/fibcalculator-client ./client
    - docker build -t nitinrai17/fibcalculator-nginx ./nginx
    - docker build -t nitinrai17/fibcalculator-server ./server
    - docker build -t nitinrai17/fibcalculator-worker ./worker
    # login into docker hub 
    - echo "$DOCKER_PASSWORD" | docker login -u "@DOCKER_ID" --password-stdin
    #  take those image and push into the docker hub
    - docker push 
    - docker push  nitinrai17/fibcalculator-client 
    - docker push  nitinrai17/fibcalculator-nginx 
    - docker push  nitinrai17/fibcalculator-server
    - docker push  nitinrai17/fibcalculator-worker